const $ = (selector, root = document) => root.querySelector(selector);
const state = { works: [], tags: { groups: [] }, current: null, editing: null, revision: null, token: "" };
const form = $("#form");

async function request(path, options = {}) {
  const response = await fetch(path, { ...options, headers: { "content-type": "application/json", ...(state.token ? { "x-admin-token": state.token } : {}), ...(options.headers ?? {}) } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `请求失败（${response.status}）`);
  return data;
}

function notify(message, error = false) { const node = $("#notice"); node.hidden = !message; node.textContent = message || ""; node.className = `notice${error ? " error" : ""}`; }
function csv(value) { return value.split(",").map((item) => item.trim()).filter(Boolean); }
function roleMap(root) { const result = {}; for (const row of root.querySelectorAll(".person-row")) { const role = $(".role", row).value.trim(); const people = csv($(".names", row).value); if (role && people.length) result[role] = people; } return result; }
function mergePeople(base, override) { const result = Object.fromEntries(Object.entries(base).map(([role, people]) => [role, [...people]])); for (const [role, people] of Object.entries(override)) result[role] = [...people]; return result; }
function renderPreview() { const base = roleMap($("#work-people")); const target = $("#people-preview"); target.innerHTML = [...$("#versions").children].map((node) => { const people = mergePeople(base, roleMap($(".version-people", node))); const text = Object.entries(people).map(([role, names]) => `${escapeHtml(role)}：${escapeHtml(names.join("、"))}`).join("；") || "暂无人员资料"; return `<div class="preview-item"><strong>${escapeHtml($(".version-name", node).value || "未命名版本")}</strong><span>${text}</span></div>`; }).join(""); }
function appendPeople(container, role = "", people = []) { const row = $("#people-row").content.cloneNode(true).firstElementChild; $(".role", row).value = role; $(".names", row).value = people.join(", "); $(".remove", row).addEventListener("click", () => row.remove()); container.append(row); }
function renderTags(selected = []) { $("#tags").innerHTML = state.tags.groups.map((group) => `<div><span class="label">${escapeHtml(group.name)}</span><div class="tag-group">${group.tags.map((tag) => `<label class="tag"><input type="checkbox" name="tag" value="${escapeHtml(tag.id)}" ${selected.includes(tag.id) ? "checked" : ""}>${escapeHtml(tag.name)}</label>`).join("")}</div></div>`).join(""); }
function renderList() { const needle = $("#work-filter").value.toLowerCase(); $("#work-list").innerHTML = `<button class="work-item ${state.editing === null ? "active" : ""}" data-new>新建作品</button>${state.works.filter((work) => `${work.title} ${work.id}`.toLowerCase().includes(needle)).map((work) => `<button class="work-item ${state.editing === work.id ? "active" : ""}" data-id="${escapeHtml(work.id)}">${escapeHtml(work.title)}<small>${escapeHtml(work.id)}</small></button>`).join("")}`; $("[data-new]").addEventListener("click", () => resetForm()); for (const button of $("#work-list").querySelectorAll("[data-id]")) button.addEventListener("click", () => loadEditor(button.dataset.id)); }
function resetForm() { state.editing = null; state.revision = null; form.reset(); $("[name=id]").disabled = false; $("#form-title").textContent = "新建作品"; $("#work-people").innerHTML = ""; $("#versions").innerHTML = ""; appendPeople($("#work-people")); addVersion(); renderTags(); renderPreview(); $("#resource-state").textContent = "未选择资源"; notify(""); renderList(); }
function addVersion(version = {}) { const node = document.createElement("div"); node.className = "version"; node.innerHTML = `<div class="version-head"><input class="input version-id" placeholder="版本 ID" value="${escapeHtml(version.id ?? "")}" required><input class="input version-name" placeholder="版本名称" value="${escapeHtml(version.name ?? "")}" required><input class="input version-type" placeholder="类型" value="${escapeHtml(version.type ?? "正式版")}" required><input class="input version-date" placeholder="日期 YYYY-MM-DD" value="${escapeHtml(version.date ?? "")}"><label class="featured"><input type="checkbox" ${version.featured ? "checked" : ""}>重点</label><span><button type="button" class="icon-button move-up" title="上移">↑</button><button type="button" class="icon-button move-down" title="下移">↓</button><button type="button" class="icon-button version-remove" title="删除">×</button></span></div><div class="version-body"><div class="section-head"><span class="label">版本人员差异</span><button type="button" class="button button--quiet add-version-people">添加角色</button></div><div class="version-people rows"></div><div class="section-head"><span class="label">链接</span><button type="button" class="button button--quiet add-link">添加链接</button></div><div class="links"></div><div class="audio-section"><div class="section-head"><span class="label">可下载音频</span><button type="button" class="button button--quiet add-audio">添加音质</button></div><p class="muted">仅可上传 MP3 或 FLAC；文件最大 100 MB。</p><div class="audio-list"></div><label class="audio-rights"><input type="checkbox" class="audio-rights-input" ${version.audioRights === "authorized" ? "checked" : ""}>确认拥有这些音频的分发权</label></div><label>备注<textarea class="input version-notes" rows="2">${escapeHtml(version.notes ?? "")}</textarea></label></div>`; $("#versions").append(node); $(".version-remove", node).addEventListener("click", () => { node.remove(); renderPreview(); }); $(".move-up", node).addEventListener("click", () => { const previous = node.previousElementSibling; if (previous) node.parentElement.insertBefore(node, previous); }); $(".move-down", node).addEventListener("click", () => { const next = node.nextElementSibling; if (next) node.parentElement.insertBefore(next, node); }); $(".add-version-people", node).addEventListener("click", () => { appendPeople($(".version-people", node)); renderPreview(); }); $(".add-link", node).addEventListener("click", () => addLink($(".links", node))); $(".add-audio", node).addEventListener("click", () => addAudio($(".audio-list", node))); for (const [role, people] of Object.entries(version.people ?? {})) appendPeople($(".version-people", node), role, people); for (const link of version.links ?? []) addLink($(".links", node), link); for (const audio of version.audio ?? []) addAudio($(".audio-list", node), audio); }
function addLink(container, link = {}) { const row = document.createElement("div"); row.className = "link-row"; row.innerHTML = `<input class="input link-platform" placeholder="平台" value="${escapeHtml(link.platform ?? "")}"><input class="input link-url" placeholder="https://..." value="${escapeHtml(link.url ?? "")}"><input class="input link-label" placeholder="用途标签" value="${escapeHtml(link.label ?? "")}"><button type="button" class="icon-button link-remove">×</button>`; container.append(row); $(".link-remove", row).addEventListener("click", () => row.remove()); }
function addAudio(container, audio = {}) { const row = document.createElement("div"); row.className = "audio-row"; row.innerHTML = `<input class="input audio-quality" placeholder="音质，如 FLAC 无损" value="${escapeHtml(audio.quality ?? "")}" required><input class="input audio-file" type="file" accept=".mp3,.flac"><span class="audio-current muted">${escapeHtml(audio.file ?? "未选择文件")}</span><button type="button" class="icon-button audio-remove" title="删除">×</button>`; row.dataset.file = audio.file ?? ""; row.dataset.format = audio.format ?? ""; container.append(row); $(".audio-remove", row).addEventListener("click", () => row.remove()); $(".audio-file", row).addEventListener("change", () => { const file = $(".audio-file", row).files[0]; if (file) $(".audio-current", row).textContent = file.name; }); }
async function loadEditor(id) { try { const data = await request(`/api/works/${encodeURIComponent(id)}`); state.editing = id; state.revision = data.revision; const work = data.work; form.reset(); $("[name=id]").value = work.id; $("[name=id]").disabled = true; $("[name=title]").value = work.title; $("[name=year]").value = work.year ?? ""; $("[name=aliases]").value = work.aliases.join(", "); $("[name=summary]").value = work.summary; $("#form-title").textContent = `编辑：${work.title}`; $("#work-people").innerHTML = ""; for (const [role, people] of Object.entries(work.people)) appendPeople($("#work-people"), role, people); $("#versions").innerHTML = ""; for (const version of data.versions) addVersion({ ...version, featured: work.featuredVersions.includes(version.id) }); renderTags(work.tags); renderPreview(); $("#resource-state").textContent = `当前封面：${work.cover ?? "无"}；歌词：${work.lyrics ?? "无"}`; notify(""); renderList(); } catch (error) { notify(error.message, true); } }
function collectPayload() { const work = { schemaVersion: 1, id: $("[name=id]").value.trim(), title: $("[name=title]").value.trim(), aliases: csv($("[name=aliases]").value), year: $("[name=year]").value.trim() ? Number($("[name=year]").value) : null, tags: [...form.querySelectorAll("input[name=tag]:checked")].map((input) => input.value), people: roleMap($("#work-people")), cover: null, lyrics: null, summary: $("[name=summary]").value, versionOrder: [], featuredVersions: [] }; const audioUploads = {}; const versions = [...$("#versions").children].map((node) => { const id = $(".version-id", node).value.trim(); work.versionOrder.push(id); if ($(".featured input", node).checked) work.featuredVersions.push(id); const links = [...node.querySelectorAll(".link-row")].map((row) => ({ platform: $(".link-platform", row).value.trim(), url: $(".link-url", row).value.trim(), label: $(".link-label", row).value.trim() })); const audio = [...node.querySelectorAll(".audio-row")].map((row) => { const quality = $(".audio-quality", row).value.trim(); const file = $(".audio-file", row).files[0]; const format = file ? file.name.split(".").pop().toLowerCase() : row.dataset.format; return { quality, file: row.dataset.file || (file ? file.name : ""), format, row }; }); return { schemaVersion: 1, id, name: $(".version-name", node).value.trim(), type: $(".version-type", node).value.trim(), date: $(".version-date", node).value.trim() || null, people: roleMap($(".version-people", node)), links, audio, audioRights: $(".audio-rights-input", node).checked ? "authorized" : null, notes: $(".version-notes", node).value }; }); return { work, versions, audioUploads }; }
async function asset(input) { const file = input.files[0]; if (!file) return null; const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte); return { name: file.name, contentBase64: btoa(binary) }; }
async function uploadAudio(payload) {
  const workId = payload.work.id;
  for (const version of payload.versions) {
    const qualities = new Set();
    for (const audio of version.audio) {
      delete audio.row;
      if (!audio.quality || !audio.file || !["mp3", "flac"].includes(audio.format)) throw new Error(`版本 ${version.id} 的音质名称或文件无效`);
      if (qualities.has(audio.quality)) throw new Error(`版本 ${version.id} 存在重复音质：${audio.quality}`);
      qualities.add(audio.quality);
      const node = [...$("#versions").children].find((item) => $(".version-id", item).value.trim() === version.id);
      const row = node && [...node.querySelectorAll(".audio-row")].find((item) => $(".audio-quality", item).value.trim() === audio.quality);
      const file = row && $(".audio-file", row).files[0];
      if (!file) continue;
      if (file.size > 100 * 1024 * 1024) throw new Error(`音频 ${file.name} 超过 100 MB`);
      const response = await fetch(`/api/audio-upload?workId=${encodeURIComponent(workId)}&versionId=${encodeURIComponent(version.id)}`, { method: "POST", headers: { "x-admin-token": state.token, "x-audio-name": encodeURIComponent(file.name), "content-type": file.type || "application/octet-stream" }, body: file });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data.error || `音频上传失败（${response.status}）`);
      payload.audioUploads[`${version.id}:${audio.quality}`] = { uploadId: data.uploadId };
    }
    if (version.audio.length && version.audioRights !== "authorized") throw new Error(`版本 ${version.id} 已添加音频，请确认拥有分发权`);
  }
}
async function save(event) { event.preventDefault(); try { const payload = collectPayload(); payload.coverAsset = await asset($("#cover")); payload.lyricsAsset = await asset($("#lyrics")); payload.revision = state.revision; await uploadAudio(payload); const path = state.editing ? `/api/works/${encodeURIComponent(state.editing)}` : "/api/works"; const saved = await request(path, { method: state.editing ? "PUT" : "POST", body: JSON.stringify(payload) }); state.revision = saved.revision; notify("已保存。请点击“校验曲库”确认内容，然后检查 Git diff。" ); state.works = await request("/api/works"); renderList(); if (!state.editing) await loadEditor(payload.work.id); } catch (error) { notify(error.message, true); } }
async function validate() { try { const result = await request("/api/validate", { method: "POST", body: "{}" }); notify(`${result.message}，当前 ${result.works} 个作品。工具不会提交或推送 Git。`); } catch (error) { notify(error.message, true); } }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]); }

$("#new-work").addEventListener("click", resetForm); $("#add-version").addEventListener("click", () => { addVersion(); renderPreview(); }); $("#validate").addEventListener("click", validate); $("#work-filter").addEventListener("input", renderList); $("[data-add-people='work']").addEventListener("click", () => { appendPeople($("#work-people")); renderPreview(); }); form.addEventListener("submit", save); form.addEventListener("input", renderPreview);
request("/api/session").then((session) => { state.token = session.token; return Promise.all([request("/api/tags"), request("/api/works")]); }).then(([tags, works]) => { state.tags = tags.tags; state.tagRevision = tags.revision; state.works = works; resetForm(); }).catch((error) => notify(error.message, true));
