import { createHash } from "node:crypto";
import { execFile as execFileCallback } from "node:child_process";
import { promisify } from "node:util";
import { cpSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import { buildWorkIndex, contentPaths, writeWorkIndex } from "./content-lib";
import type { TagCatalog, Version, Work } from "../src/content/types";
const execFile = promisify(execFileCallback);

export const ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export interface Upload { name: string; contentBase64: string }
export interface WorkInput { work: Work; versions: Version[]; revision?: string; coverAsset?: Upload | null; lyricsAsset?: Upload | null }
export class AdminError extends Error { constructor(message: string, public status = 400) { super(message); } }

export function checkId(id: unknown): asserts id is string { if (typeof id !== "string" || !ID_PATTERN.test(id)) throw new AdminError("ID 必须使用小写英文、数字和连字符"); }
function regularTree(path: string): void { const stat = lstatSync(path); if (stat.isSymbolicLink()) throw new AdminError("内容目录不支持符号链接"); if (stat.isDirectory()) for (const name of readdirSync(path)) regularTree(join(path, name)); else if (!stat.isFile()) throw new AdminError("内容目录只能包含普通文件和目录"); }
export function revision(path: string): string { regularTree(path); const hash = createHash("sha256"); const walk = (dir: string, prefix: string) => { for (const name of readdirSync(dir).sort()) { const file = join(dir, name); if (lstatSync(file).isDirectory()) walk(file, `${prefix}${name}/`); else hash.update(`${prefix}${name}\0`).update(readFileSync(file)).update("\0"); } }; walk(path, ""); return hash.digest("hex"); }
const readJson = (path: string) => JSON.parse(readFileSync(path, "utf8"));
function writeJson(path: string, value: unknown): void { writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`); }

export function readEditorWork(root: string, id: string) { checkId(id); const paths = contentPaths(root); regularTree(paths.content); const dir = join(paths.works, id); if (!existsSync(dir)) throw new AdminError("作品不存在", 404); const work = readJson(join(dir, "work.json")) as Work; const versions = readdirSync(dir).filter((name) => /^version-.+\.json$/.test(name)).map((name) => readJson(join(dir, name)) as Version); versions.sort((a, b) => work.versionOrder.indexOf(a.id) - work.versionOrder.indexOf(b.id)); return { work, versions, revision: revision(dir) }; }
export function readEditorTags(root: string) { const paths = contentPaths(root); regularTree(paths.content); const tags = readJson(paths.tags) as TagCatalog; return { tags, revision: createHash("sha256").update(readFileSync(paths.tags)).digest("hex") }; }
function snapshot(root: string): string { const paths = contentPaths(root); regularTree(paths.content); const temp = mkdtempSync(join(tmpdir(), "yousa-admin-")); try { cpSync(paths.content, contentPaths(temp).content, { recursive: true }); return temp; } catch (error) { rmSync(temp, { recursive: true, force: true }); throw error; } }

function upload(dir: string, asset: Upload, kind: "cover" | "lyrics"): string { if (!asset || typeof asset.name !== "string" || basename(asset.name) !== asset.name || asset.name.includes("\\")) throw new AdminError("资源文件名无效"); const ext = asset.name.slice(asset.name.lastIndexOf(".")).toLowerCase(); const allowed = kind === "cover" ? [".png", ".jpg", ".jpeg", ".webp"] : [".txt"]; if (!allowed.includes(ext)) throw new AdminError("资源文件扩展名不受支持"); if (typeof asset.contentBase64 !== "string" || !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(asset.contentBase64)) throw new AdminError("文件编码无效"); const bytes = Buffer.from(asset.contentBase64, "base64"); if (!bytes.length || bytes.length > (kind === "cover" ? 8 : 2) * 1024 * 1024) throw new AdminError("资源文件大小不符合限制"); if (kind === "lyrics") { try { new TextDecoder("utf-8", { fatal: true }).decode(bytes); } catch { throw new AdminError("歌词须使用 UTF-8 编码"); } } else { const valid = ext === ".png" ? bytes.subarray(0, 8).equals(Buffer.from("89504e470d0a1a0a", "hex")) : ext === ".webp" ? bytes.toString("ascii", 0, 4) === "RIFF" && bytes.toString("ascii", 8, 12) === "WEBP" : bytes.subarray(0, 3).equals(Buffer.from("ffd8ff", "hex")); if (!valid) throw new AdminError("封面内容与图片扩展名不符"); } const name = kind === "lyrics" ? "lyrics.txt" : `cover${ext}`; writeFileSync(join(dir, name), bytes); return name; }
function checkLinks(versions: Version[]): void { for (const version of versions) for (const link of version.links ?? []) { try { const url = new URL(link.url); if (!["http:", "https:"].includes(url.protocol) || !url.hostname || /\s/.test(link.url)) throw new Error(); } catch { throw new AdminError(`版本 ${version.id} 的链接格式无效`); } } }

export function saveEditorWork(root: string, input: WorkInput, editingId?: string) { if (!input?.work || !Array.isArray(input.versions)) throw new AdminError("请求内容不完整"); const id = input.work.id; checkId(id); if (editingId !== undefined && editingId !== id) throw new AdminError("编辑时不能修改作品 ID"); const paths = contentPaths(root); regularTree(paths.content); const dir = join(paths.works, id); if (editingId === undefined && existsSync(dir)) throw new AdminError("作品 ID 已存在", 409); if (editingId !== undefined && !existsSync(dir)) throw new AdminError("作品不存在", 404); const old = editingId !== undefined ? readEditorWork(root, id) : null; if (old && input.revision !== old.revision) throw new AdminError("文件已被其他页面或编辑器修改，请重新打开作品", 409); const ids = input.versions.map((v) => { checkId(v?.id); return v.id; }); if (!ids.length || new Set(ids).size !== ids.length) throw new AdminError("版本 ID 不能为空且不能重复"); if (!Array.isArray(input.work.versionOrder) || input.work.versionOrder.length !== ids.length || new Set(input.work.versionOrder).size !== ids.length || input.work.versionOrder.some((v) => !ids.includes(v))) throw new AdminError("版本顺序须包含全部版本且不重复"); if (input.work.featuredVersions.length > 3 || input.work.featuredVersions.some((v) => !ids.includes(v))) throw new AdminError("重点版本最多 3 个且必须存在"); checkLinks(input.versions);
  const temp = snapshot(root); let stage: string | undefined; let backup: string | undefined; try { const stagedDir = join(contentPaths(temp).works, id); mkdirSync(stagedDir, { recursive: true }); const work = { ...old?.work, ...input.work }; if (old && !input.coverAsset) work.cover = old.work.cover; if (old && !input.lyricsAsset) work.lyrics = old.work.lyrics; if (input.coverAsset) work.cover = upload(stagedDir, input.coverAsset, "cover"); if (input.lyricsAsset) work.lyrics = upload(stagedDir, input.lyricsAsset, "lyrics"); writeJson(join(stagedDir, "work.json"), work); for (const file of readdirSync(stagedDir)) if (/^version-.+\.json$/.test(file)) rmSync(join(stagedDir, file)); for (const version of input.versions) { const original = old?.versions.find((v) => v.id === version.id); writeJson(join(stagedDir, `version-${version.id}.json`), { ...original, ...version }); } buildWorkIndex(temp); if (old && revision(dir) !== old.revision) throw new AdminError("保存期间文件已发生变化，请重新打开作品", 409); stage = mkdtempSync(join(paths.works, ".admin-stage-")); cpSync(stagedDir, join(stage, id), { recursive: true }); if (old) { backup = join(stage, "previous"); renameSync(dir, backup); } try { renameSync(join(stage, id), dir); } catch (error) { if (backup) renameSync(backup, dir); throw error; } if (backup) { rmSync(backup, { recursive: true }); backup = undefined; } return readEditorWork(root, id); } finally { rmSync(temp, { recursive: true, force: true }); if (stage && !backup) rmSync(stage, { recursive: true, force: true }); } }

export function saveEditorTags(root: string, tags: TagCatalog, expectedRevision: string) { const original = readEditorTags(root); if (original.revision !== expectedRevision) throw new AdminError("标签文件已变化，请重新读取", 409); const temp = snapshot(root); try { writeJson(contentPaths(temp).tags, tags); buildWorkIndex(temp); const target = contentPaths(root).tags; const stage = `${target}.admin-tmp`; writeJson(stage, tags); renameSync(stage, target); return readEditorTags(root); } finally { rmSync(temp, { recursive: true, force: true }); } }

export function validateEditor(root: string) { const temp = snapshot(root); try { const index = writeWorkIndex(temp); return { ok: true, works: index.works.length, message: "内容校验通过；临时索引已生成，正式索引未被修改" }; } finally { rmSync(temp, { recursive: true, force: true }); } }

export async function validateEditorBuild(root: string, projectRoot: string) { const temp = snapshot(root); try { const index = writeWorkIndex(temp); await execFile(process.execPath, [join(projectRoot, "node_modules/typescript/bin/tsc"), "-b", "--pretty", "false"], { cwd: projectRoot, timeout: 120_000 }); await execFile(process.execPath, [join(projectRoot, "node_modules/vite/bin/vite.js"), "build", "--outDir", join(temp, "dist"), "--emptyOutDir"], { cwd: projectRoot, timeout: 120_000, env: { ...process.env, PUBLIC_DIR: join(temp, "public"), VITE_BASE_PATH: "/yousa-song-archive/" } }); return { ok: true, works: index.works.length, message: "内容校验、类型检查和子路径构建均通过；正式索引未被修改" }; } catch (error) { const failure = error as Error & { stdout?: string; stderr?: string }; throw new AdminError([failure.message, failure.stdout, failure.stderr].filter(Boolean).join("\n")); } finally { rmSync(temp, { recursive: true, force: true }); } }
